export const popularIndianStocks = [
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "ITC", name: "ITC Limited" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "LTMINDTREE", name: "LTIMindtree" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA", name: "Sun Pharma" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "TITAN", name: "Titan Company" },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "NTPC", name: "NTPC Limited" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "NESTLEIND", name: "Nestle India" },
  { symbol: "POWERGRID", name: "Power Grid Corp" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "ONGC", name: "ONGC" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products" },
  { symbol: "HINDALCO", name: "Hindalco Industries" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "DRREDDY", name: "Dr Reddy's Labs" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "BRITANNIA", name: "Britannia Industries" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE", name: "HDFC Life" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "UPL", name: "UPL" },
  { symbol: "BPCL", name: "BPCL" }
];
